name: Spotify Metrics

on:
  schedule:
    - cron: "0 */4 * * *" 
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Spotify Music Plugin
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.recent.svg
          
          token: NOT_NEEDED
          base: ""

          extras_css: |
            :root {
              --color-text-primary: #f8f8f2;     /* Branco Suave */
              --color-text-secondary: #bd93f9;   /* Roxo Dracula */
              --color-background: #282a36;       /* Fundo Escuro */
            }
            .field, .field svg { fill: #f8f8f2 !important; color: #f8f8f2 !important; }
            .header { color: #50fa7b !important; } /* Verde para títulos */
          
          # Configurações do Spotify
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 3
