name: Update Spotify Stats

on:
  schedule:
    # Roda a cada 6 horas
    - cron: "0 */6 * * * "
  workflow_dispatch: # Permite você clicar num botão para testar agora mesmo

jobs:
  update-readme:
    name: Update Spotify Stats in README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Spotify Stats Action
        uses: GitGinocchio/SpotifyStatsAction@v0.5-beta.4
        with:
          # O caminho do seu README (padrão é README.md)
          readme_list: "README.md"
          
          # Mostra as ultimas musicas ouvidas
          update_last_played_songs: true
          last_played_songs_to_show: 5
          
          # Mostra seus top artistas
          update_user_top_artists: true
          top_artists_to_show: 5
        env:
          # AQUI ESTÁ O TRUQUE: Você precisa configurar esses segredos no repo
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
